import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for Module 1 - ROS 2
  module01Sidebar: [
    {
      type: 'category',
      label: 'Module 1 - The Robotic Nervous System (ROS 2)',
      items: [
        'module-01/chapter-1-ros2-fundamentals',
        'module-01/chapter-2-agent-ros-bridge',
        'module-01/chapter-3-urdf-modeling',
      ],
    },
  ],

  // Manual sidebar for Module 2 - Digital Twin
  module02Sidebar: [
    {
      type: 'category',
      label: 'Module 2 - The Digital Twin (Gazebo & Unity)',
      items: [
        'module-02/chapter-1-gazebo-physics',
        'module-02/chapter-2-sensor-simulation',
        'module-02/chapter-3-unity-digital-twin',
      ],
    },
  ],

  // Manual sidebar for Module 3 - Isaac AI Brain
  module03Sidebar: [
    {
      type: 'category',
      label: 'Module 3 - The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'module-03/isaac-ai-brain/isaac-sim',
        'module-03/isaac-ai-brain/isaac-ros',
        'module-03/isaac-ai-brain/nav2-navigation',
      ],
    },
  ],

  // Manual sidebar for Module 4 - Vision-Language-Action
  module04Sidebar: [
    {
      type: 'category',
      label: 'Module 4 - Vision-Language-Action (VLA)',
      items: [
        'module-04/vla/voice-to-action',
        'module-04/vla/cognitive-planning',
        'module-04/vla/capstone',
      ],
      collapsed: false,  // Expand by default for better visibility
    },
  ],
};

export default sidebars;
